language: cpp

os:
  - linux

compiler:
  - g++
  - clang++


addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - boost1.67
      - g++-5
      - clang-3.6

install:
  - if [[ "${CXX}" = "g++" ]]; then export CXX="g++-5"; fi
  - if [[ "${CXX}" = "clang++" ]]; then export CXX="clang++-3.6"; fi

script:
  - cmake .
  - make
  - make test
